export const CompanyCategories = [
  'B2B',
  'B2C',
  'Banking & Mortgages',
  'Beverages',
  'Biotechnology',
  'Broadcasting',
  'Building Materials',
  'Business Supplies',
  'Chemicals',
  'Civil Engineering',
  'Cloud Services',
  'Communications',
  'Computer Hardware',
  'Construction',
  'Construction Contractors & Services',
  'Consulting & Professional Services',
  'Consumer Discretionary',
  'Consumer Electronics',
  'Consumer Goods',
  'Consumer Staples',
  'Coporate & Business',
  'Cosmetics',
  'Design',
  'E-Commerce',
  'E-Commerce & Marketplaces',
  'E-Learning',
  'Education',
  'Electrical',
  'Energy',
  'Energy & Utilities',
  'Enterprise',
  'Entertainment & Recreation',
  'Events',
  'Eyewear',
  'Facilities',
  'Financial Services',
  'Fine Art',
  'Firearms',
  'Fishery',
  'Food',
  'Food Production',
  'Forums',
  'Fundraising',
  'Gambling & Casinos',
  'Government',
  'Ground Transportation',
  'Health & Wellness',
  'Health Care',
  'Higher Education',
  'Home & Furniture',
  'Home Improvement',
  'Human Resources',
  'Import & Export',
  'Industrials & Manufacturing',
  'Information Technology & Services',
  'Insurance',
  'International Relations',
  'International Trade',
  'Internet',
  'Investment',
  'Investment Banking',
  'Investment Management',
  'ISP',
  'Jewelry Watching & Luxury Goods',
  'Judiciary',
  'Law Enforcement',
  'Libraries',
  'Machinery',
  'Maritime',
  'Market Research',
  'Marketing & Advertising',
  'Marketplace',
  'Mechanical Engineering',
  'Media',
  'Medicine',
  'Military',
  'Mining & Metals',
  'Mobile',
  'Movies & TV',
  'Museums',
  'Music',
  'Nanotechnology',
  'Networking',
  'Non-Profit & Philanthropy',
  'Oil & Gas',
  'Outsourcing',
  'Packaging & Containers',
  'Paper Goods',
  'Payments',
  'Performing Arts',
  'Pharmaceuticals',
  'Pharmacy',
  'Photography',
  'Plastics',
  'Plumbing',
  'Political Organization',
  'Pornography',
  'Printing',
  'Public Relations',
  'Publishing',
  'Ranching',
  'Real Estate',
  'Religion',
  'Renewables & Environment',
  'Restaurants',
  'Retail',
  'SAAS',
  'Sanitization & Academic Research',
  'Security',
  'Services',
  'Shipbuilding',
  'Shipping & Logistics',
  'Society',
  'Sporting Goods',
  'Sports & Fitness',
  'Stores',
  'Talent Agencies',
  'Technology',
  'Telecommunications',
  'Textiles',
  'Tobacco',
  'Tools',
  'Translation',
  'Transportation',
  'Travel & Leisure',
  'Utilities',
  'Venture Capital',
  'Veterinary',
  'Video Games',
  'Warehousing',
  'Web Services & Apps',
  'Wholesale',
];
